<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="first_robot">
    <xacro:include filename="$(find firstrobot_description)/urdf/fishbot/common_inertia.xacro"/>
    <xacro:macro name="base_xacro" params="length radius">
        <link name="base_footprint_link"/>
        <link name="base_link">
            <visual>
                <!-- 沿几何中心的偏移量 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <!-- 圆柱半径和高度 -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </visual>
            <collision>
                 <!-- 沿几何中心的偏移量 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <!-- 圆柱半径和高度 -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>
        </link>

         <joint name="base_footprint_joint" type="fixed">
            <origin xyz="0.0 0.0 ${length/2+0.032-0.001}" rpy="0.0 0.0 0.0"/>
            <parent link="base_footprint_link"/>                                                                                                               
            <child link="base_link"/> 
        </joint>

        <gazebo reference="base_link">
            <material>Gazebo/White</material>
         </gazebo>
    </xacro:macro>
    
</robot>



    
